<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8DQ5F38" failures="1" tests="1" name="Test(failed)(failed)" time="6.701" errors="0" timestamp="2023-09-26T17:16:34 IST">
  <testcase classname="TestPackage.TestClass2" name="VerifyBackToProductButton" time="3.018">
    <failure type="java.lang.AssertionError" message="did not expect [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/inventory.html]
at TestPackage.TestClass2.VerifyBackToProductButton(TestClass2.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- VerifyBackToProductButton -->
</testsuite> <!-- Test(failed)(failed) -->
